# NumPy Exercises 

## Exercise 1

Basic array operations.

import NumPy as np

Create an array of 10 zeros 

In [8]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Create an array of 10 ones

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [14]:
np.arange(5,5,10)

array([], dtype=int32)

Create an array of the integers from 10 to 50

In [19]:
np.random.randint(10,50,51)

array([22, 48, 35, 36, 19, 27, 45, 40, 19, 44, 15, 31, 34, 21, 39, 45, 48,
       40, 49, 40, 16, 20, 18, 36, 29, 13, 28, 27, 21, 10, 27, 44, 27, 33,
       48, 40, 21, 15, 23, 46, 30, 43, 45, 43, 47, 31, 18, 38, 37, 38, 22])

Create an array of all the even integers from 10 to 50

In [21]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
arr= np.arange(0,9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [26]:
np.random.rand(1)

array([0.30043526])

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [27]:
np.random.randn(5,5)

array([[ 1.56736892,  0.56844893,  0.27778023, -0.7756417 ,  0.57020292],
       [ 1.38552488, -1.46968209, -1.89648844,  1.38525318, -0.06826567],
       [-1.54337272,  0.99751718, -2.49457287,  0.03124262, -0.86627743],
       [ 0.88940693,  1.23278554,  0.11244399,  0.41914328,  1.08315226],
       [ 2.21970072, -0.11232833, -0.28869284,  0.45742536, -1.01062476]])

Create the following matrix:

Create an array of 20 linearly spaced points between 0 and 1:

In [32]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Exercsie 2

Numpy Indexing and Selection: given a few matrices, write code that will produce the resulting matrix outputs:

In [43]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[3][4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [48]:
mat[:,1]

array([ 2,  7, 12, 17, 22])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [51]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Exercise 3

Get the sum of all the values in mat

In [53]:
sum(sum(mat))

325

Get the standard deviation of the values in mat

7.2111025509279782

Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])